spring:
  profiles:
    active: dev

springfox.documentation.swagger.v2.path: /v2/api-docs

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # Entity Scanning
  typeAliasesPackage: com.jitlantis.backend.API.model

  global-config:
    # 0:"autoincrement ID", 1:"user-input ID",2:"unique ID (unique ID)", 3:"unique ID UUID";
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    # capital-underscore convert
    # capital-mode: true
    # key-generator: com.baomidou.springboot.xxx

    # logic delete
    logic-delete-value: 1
    logic-not-delete-value: 0
    # meta-object-handler: com.baomidou.springboot.xxx
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    key-generator:

  configuration:
    mapUnderscoreToCamelCase: true
    cache-enabled: false
    call-setters-on-nulls: true

# Logger Config
logging:
  level:
    com.phiotonia.kniotcloud.backend: debug
